<!-- $Id: main.inc,v 1.3 2005/03/04 02:10:47 rswindell Exp $ -->

<!-- Main Content --> 
</td>

    <td class="main" valign="top"><br />
        <br />
       
       <div align="center"><h3>Your sysop, <i>@@JS:system.operator@@</i>, welcomes you to 
        <b>@@JS:system.name@@</b></h3></div>
                
        <table align="center">
          <tr>
          <td align="center">Today's Statistics<br /><br />
          
            <!--  Stats go here and table is closed by index.ssjs -->
            
<!-- end Main Content -->
