<!-- $Id: themes.inc,v 1.6 2005/03/04 00:59:14 runemaster Exp $ -->

<!-- Main Content -->  
    
    <td class="main" valign="top"><br />


<table class="theme" cellspacing="2" cellpadding="2">
    <tbody>
        <tr>
        <td class="theme">
            <form action="picktheme.ssjs" method="post">
                <br />
                @@theme_list@@<br /><br />
                <input type="submit" name="Select Theme" value="Select Theme" />
            </form>
        </td>
        </tr>
    </tbody>
</table>


<!-- end Main Content -->